In [3]:
import pandas as pd
import pickle
import numpy as np
from sklearn.linear_model import SGDClassifier
from sklearn.metrics import classification_report

career = pd.read_csv('dataset9000.data', header = None)
#np.dtype('float64')

X = np.array(career.iloc[:,0:17]) #X is skills
print(X)
y = np.array(career.iloc[:,17]) #Y is Roles
print("hi")
print(y)
# class_names=career.target_names
##  attribute to return the column labels of the given Dataframe
career.columns = ["Database Fundamentals","Computer Architecture","Distributed Computing Systems",
"Cyber Security","Networking","Development","Programming Skills","Project Management",
"Computer Forensics Fundamentals","Technical Communication","AI ML","Software Engineering","Business Analysis",
"Communication skills","Data Science","Troubleshooting skills","Graphics Designing","Roles"]

career.dropna(how ='all', inplace = True)
#print("career.dropna(how ='all', inplace = True)",career.dropna(how ='all', inplace = True))
career.head()
## splitting the data into training and test sets

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size = 0.3, random_state = 524)
sgdc = SGDClassifier(max_iter=6, tol=0.12)
sgdc.fit(X_train, y_train)
y_pred = sgdc.predict(X_test)
score = sgdc.score(X_train, y_train)
from sklearn import metrics
scores = {}
print(classification_report(y_test,y_pred))



scores[5] = metrics.accuracy_score(y_test, y_pred)
print('Accuracy=',scores[5]*100)






[[9 1 1 ... 1 1 1]
 [9 2 1 ... 1 1 1]
 [9 3 1 ... 1 1 1]
 ...
 [1 1 1 ... 6 6 9]
 [1 1 1 ... 7 7 9]
 [1 1 1 ... 7 5 9]]
hi
['Database Administrator' 'Database Administrator'
 'Database Administrator' ... 'Graphics Designer' 'Graphics Designer'
 'Graphics Designer']
                                 precision    recall  f1-score   support

               AI ML Specialist       1.00      0.98      0.99       154
     API Integration Specialist       1.00      1.00      1.00       175
   Application Support Engineer       1.00      1.00      1.00       159
               Business Analyst       1.00      1.00      1.00       156
     Customer Service Executive       0.99      1.00      0.99       166
      Cyber Security Specialist       1.00      0.77      0.87       151
                 Data Scientist       0.99      0.89      0.94       160
         Database Administrator       1.00      1.00      1.00       155
              Graphics Designer       1.00      1.00      1.00       155
   

e:\frontend\MARG-DARSHAK\pythoncode\.venv\Lib\site-packages\sklearn\linear_model\_stochastic_gradient.py:744: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  warnings.warn(
