In [1]:
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.svm import SVC
import pandas as pd
import pickle
import numpy as np
from sklearn.metrics import classification_report
career = pd.read_csv('dataset9000.data', header=None)


X = np.array(career.iloc[:, 0:17])  # X is skills
print(X)
y = np.array(career.iloc[:, 17])  # Y is Roles
print(y)

# attribute to return the column labels of the given Dataframe
career.columns = ["Database Fundamentals", "Computer Architecture", "Distributed Computing Systems",
                  "Cyber Security", "Networking", "Development", "Programming Skills", "Project Management",
                  "Computer Forensics Fundamentals", "Technical Communication", "AI ML", "Software Engineering", "Business Analysis",
                  "Communication skills", "Data Science", "Troubleshooting skills", "Graphics Designing", "Roles"]

career.dropna(how='all', inplace=True)

career.head()

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.80, random_state=524)

classifier = SVC(kernel='rbf')
scores = {}


classifier.fit(X_train, y_train)
print('X_train', X_train)
print('y_train', y_train)
y_pred = classifier.predict(X_test)
print('y_pred', y_pred)
scores[5] = metrics.accuracy_score(y_test, y_pred)
print('Accuracy=', scores[5]*100)
print(classification_report(y_test, y_pred))




[[9 1 1 ... 1 1 1]
 [9 2 1 ... 1 1 1]
 [9 3 1 ... 1 1 1]
 ...
 [1 1 1 ... 6 6 9]
 [1 1 1 ... 7 7 9]
 [1 1 1 ... 7 5 9]]
['Database Administrator' 'Database Administrator'
 'Database Administrator' ... 'Graphics Designer' 'Graphics Designer'
 'Graphics Designer']
X_train [[6 6 6 ... 2 6 6]
 [5 5 5 ... 5 5 5]
 [3 3 3 ... 3 3 3]
 ...
 [3 3 3 ... 3 3 3]
 [1 1 1 ... 1 1 1]
 [2 9 2 ... 2 6 6]]
y_train ['Technical Writer' 'Project Manager' 'Networking Engineer' ...
 'Software Developer' 'AI ML Specialist' 'Hardware Engineer']
y_pred ['Software Tester' 'Hardware Engineer' 'Customer Service Executive' ...
 'Application Support Engineer' 'Database Administrator'
 'Hardware Engineer']
Accuracy= 99.18300653594771
                                 precision    recall  f1-score   support

               AI ML Specialist       1.00      0.98      0.99       428
     API Integration Specialist       0.99      0.99      0.99       445
   Application Support Engineer       0.98      1.00      0.99       